<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Logging</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Setting up message logging (errors, debug information, etc.) of your web application.</p>

    <h2>Contens:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('form') ?>">Logging setup form</a></li>
    </ul>
</article>